# This is a basic workflow that is manually triggered

name: Build app via Cloudbuild

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
       
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
     
    - name: 'Deploy app to Cloudrun'
      run: 'gcloud run deploy github-to-gcd --image=gcr.io/calm-analog-341912/assignment-3 --region=us-central1 --allow-unauthenticated'
